name: Docker
on:
  push:
    branches:
      - master

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        name: Build Docker Image
        with:
          username: basmakes
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: basmakes/potatoauth-site